apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: Sync ArgoCD Application with Kubernetes
    uses: omegion/argocd-actions@v1
    with:
      address: "http://aad18b92a45fb46d5b54b38315c44f2a-2097128699.us-east-1.elb.amazonaws.com"
      token: ${{ secrets.ARGOCD_TOKEN }}
      action: sync
      appName: "argocddemonew2"
   
spec:
    project: automationargocd
    name: argocddemonew2
    namespace: argocddemonew2

source:
  repoURL: https://github.com/tanvinaxane/testingECR.git
  targetRevision: HEAD
  path: "."

destination:
  server: https://9AF7702E15AF6E83BCB81D82DCD1C479.gr7.us-east-1.eks.amazonaws.com
  namespace: argocddemonew2

syncPolicy:
    syncOptions:
        - CreateNamespace=true

automated:
  selfHeal: true
  prune: true
