apiVersion: apps/v1
kind: Deployment
metadata:
  name: stagetoprod
  namespace: stagetoprodst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 244740641779.dkr.ecr.us-east-1.amazonaws.com/testingdockerimage:prod
          ports:
            - containerPort: 3000
