apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newstageprodapp
spec:
  destination:
    name: MetronetPocArgocd
    namespace: 'newstageprod'
    server: 'https://C7670FF6497552BFBC7284EBD87B1B2F.gr7.us-east-1.eks.amazonaws.com'
  source:
    path: .
    repoURL: 'https://github.com/tanvinaxane/testingECR.git'
    targetRevision: main
  project: newstageprodproject
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
