on:
  push:
    branches: [ main ]

env:
  SRC_ECR_REGISTRY: https://244740641779.dkr.ecr.us-east-1.amazonaws.com/
  SRC_ECR_REPOSITORY: testingdockerimage
  DEST_ECR_REGISTRY: https://244740641779.dkr.ecr.us-east-1.amazonaws.com/
  DEST_ECR_REPOSITORY: newtanvirepo
  

name: STAGE TO PROD IMAGE REPLICATION

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_TOKEN}}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
          SRC_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SRC_ECR_REPOSITORY: testingdockerimage
          SRC_IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: us-east-1
      run: |
        SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`
        ls -la
        docker build -t $SRC_ECR_REGISTRY/$SRC_ECR_REPOSITORY:$SRC_IMAGE_TAG -t $SRC_ECR_REGISTRY/$SRC_ECR_REPOSITORY:${{ github.sha }} .
        docker push $SRC_ECR_REGISTRY/$SRC_ECR_REPOSITORY:${{ github.sha }} | $DEST_ECR_REGISTRY/$DEST_ECR_REPOSITORY:${{ github.sha }} 
        echo "Pushing image to ECR"
        echo "::set-output name=image::$SRC_ECR_REGISTRY/$SRC_ECR_REPOSITORY:${{ github.sha }}"
        echo "::set-output name=image::$DEST_ECR_REGISTRY/$DEST_ECR_REPOSITORY:${{ github.sha }}"
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.8.8"

    - name: Update Kubernetes resources
      run: |
        cd ~/k8s-eks-manifest
        git pull
        git config --global user.email ${GITHUB_EMAIL}
        git config --global user.name ${GITHUB_USERNAME}
        git checkout main
        echo "Update newimage with kustomize"
        SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`
        cd kustomize/demoapp1
        kustomize edit set image $SRC_ECR_REGISTRY/$SRC_ECR_REPOSITORY:${{ github.sha }}
        cat kustomization.yaml
        git commit -am "[${{ github.repository }}] $GITHUB_ACTOR - ${{ github.event.head_commit.message }}"
        git push -u origin main 
        
    - name: Sync ArgoCD App
      run: |
        argocd --insecure app sync ${{ secrets.ARGOCD_TOKEN }}
        echo "Replicating iamge from Stage to Prod"
