on:
  push:
    branches: [ ecrautorepo ]

env:
  ECR_REGISTRY: http://244740641779.dkr.ecr.us-east-1.amazonaws.com 
  ECR_REPOSITORY: testingdockerimage
  NEW_ECR_REPO: newecrrepo1
  
name: AUTO CREATE ECR REPO IF NOT EXISTS

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_TOKEN}}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Check if ECR repo exists
      if: "!contains('$NEW_ECR_REPO', '$ECR_REGISTRY')"
      run:
        echo "Since repo doesn't exist in ECR, Creating new repo."
        
    - name: Create new repo in ECR
      uses: int128/create-ecr-repository-action@v1
      with:
        repository: $NEW_ECR_REPO
        public: true
      
    
    
  

  

        
