name: AUTO DELETION OF APPS ON MERGE

on:
  push: 
    branches: [demo] 
  workflow_dispatch:
      inputs:
        ON_MERGE:
          description: ENTER YOUR NAME
          required: true
          default: metronet
          type: string

jobs:

  push:
    name: On push operation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_TOKEN}} 
        aws-region: ${{ secrets.AWS_REGION }} 
        
    - name: Setup EKS Kubectl
      uses: zachguo/setup-eks-kubectl@v1
      with:
        cluster: metronetpocmulticluster # name of your EKS cluster
        region: ${{ secrets.AWS_REGION }}  # region of your EKS cluster
        namespace: argocddemonew2 # optional namespace context, default value is 'default'
  
    - name: Connect to your cluster
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name metronetpocmulticluster
        echo "Cluster says HI"
        
        
    
        
        
        
        
