name: Deploy to Stage

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
 deploy:
  uses: metronetinc/github-actions/.github/workflows/deploy-to-k8.yaml@v1.0.1
  with:
    repo_name: ${{ github.event.repository.name }}
    image_tag:   stage-${{ github.run_number }}
    deployment_repo: service-api-gitops
    deployment_repo_path: src/party-role/overlays/stage
    app_name: party-role
    deployment_repo_ref: main
  secrets:
    AWS_ECR_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
    AWS_ECR_SECRET_KEY: ${{ secrets.AWS_ECR_SECRET_KEY }}
    AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION }}
    GITHUB_PAT: ${{ secrets.PAT }}
    NPM_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
